#!/bin/bash

green="\033[0;32m"
red="\033[0;31m"
white="\033[0m"

if hash ruby 2>/dev/null; then
  if [ ! -d "$HOME/.enote" ]; then
    mkdir $HOME/.enote
    mkdir $HOME/.enote/notes
    cp ./lib/config_default $HOME/.enote/config
    chmod +x uninstall
  fi
else
  echo -e "${red}Ruby is required but it's not installed. Please install Ruby and then try again. Aborting.${white}"
  exit 1
fi

editor=""
while [ ! -n "$editor" ]
do
  read -p "Enter name of default text editor (e.g. 'vim', 'nano', etc.):" ans
  if [ ! -n "$ans" ]; then
    echo -e "${red}Enter a value.${white}"
  else
    if ! hash $ans 2>/dev/null; then
      echo -e "${red}Application called '$ans' not installed.${white}"
      editor=""
    else
      editor=$ans
      ./lib/enote --set-editor $editor
    fi
  fi
done

path="export PATH=\$PATH:$(pwd)/lib"
if [ -f $HOME/.bashrc ]; then
  if ! grep -Fxq "$path" "$HOME/.bashrc"; then
    echo -e "\n$path" >> $HOME/.bashrc
    echo "source $(pwd)/lib/bash_source" >> $HOME/.bashrc
    echo -e "Updated ~/.bashrc"
  fi
fi

if [ -f $HOME/.zshrc ]; then
  if ! grep -Fxq "$path" "$HOME/.zshrc"; then
    echo -e "\n$path" >> $HOME/.zshrc
    echo "fpath=($(pwd)/lib \$fpath)" >> $HOME/.zshrc
    echo "autoload _zsh_completion" >> $HOME/.zshrc
    echo "compdef _zsh_completion enote" >> $HOME/.zshrc
    echo -e "Updated ~/.zshrc"
  fi
fi

echo -e "${green}ENote installed successfully. Open a NEW terminal window to run ENote.${white}"
