#!/bin/bash

green="\033[0;32m"
red="\033[0;31m"
white="\033[0m"

if [ -d "$HOME/.enote" ]; then
  rm -r $HOME/.enote
  echo "Removed configuration directory"
fi

wd="$(pwd)/lib"
path="export PATH=\$PATH:$wd"
path2="${path//\//\\\/}"
enote_dir="\$HOME/.enote"
path3="${enote_dir//\//\\\/}"
if [ -f $HOME/.bashrc ]; then
  if grep -Fxq "$path" $HOME/.bashrc; then
    sed -i -e "/$path2/d" $HOME/.bashrc
    sed -i -e "/source $path3\\/bash_source/d" $HOME/.bashrc
    echo -e "Removed current directory from ~/.bashrc"
  fi
fi

if [ -f $HOME/.zshrc ]; then
  if grep -Fxq "$path" $HOME/.zshrc; then
    sed -i -e "/$path2/d" $HOME/.zshrc
    sed -i -e "/fpath=($path3 \$fpath)/d" $HOME/.zshrc
    sed -i -e "/autoload _zsh_completion/d" $HOME/.zshrc
    sed -i -e "/compdef _zsh_completion enote/d" $HOME/.zshrc
    echo -e "Removed current directory from ~/.zshrc"
  fi
fi

echo -e "${green}ENote uninstalled successfully"
